extends SceneTree

var _command_frames: Array[int]


func _initialize() -> void:
	call_deferred("_run")


func _run() -> void:
	var move_block: PackedByteArray = RwBattleCommandWriter.write_move(1, [42,], Vector2(120.0, 80.0))
	var raw_block: StreamPeerBuffer = RwBinary.reader(move_block)
	assert(RwBinary.read_utf(raw_block) == "c")
	var block_size: int = raw_block.get_32()
	var body: PackedByteArray = (raw_block.get_data(block_size) as Array)[1]
	var path_stream: StreamPeerBuffer = RwBinary.writer()
	path_stream.put_32(3)
	path_stream.put_16(2)
	path_stream.put_16(3)
	path_stream.put_u8(6)
	path_stream.put_u8(6)
	var compressed_path: PackedByteArray = path_stream.data_array.compress(FileAccess.COMPRESSION_GZIP)
	var target_body: StreamPeerBuffer = RwBinary.writer()
	target_body.put_32(1)
	target_body.put_64(42)
	target_body.put_float(20.0)
	target_body.put_float(30.0)
	target_body.put_float(120.0)
	target_body.put_float(80.0)
	target_body.put_32(24)
	target_body.put_32(1)
	target_body.put_u8(1)
	target_body.put_u8(1)
	RwBinary.write_utf(target_body, "p")
	target_body.put_32(compressed_path.size())
	target_body.put_data(compressed_path)
	target_body.put_u8(1)
	var complete_body: PackedByteArray = body.slice(0, body.size() - 5)
	complete_body.append_array(target_body.data_array)
	var command_block: StreamPeerBuffer = RwBinary.writer()
	RwBinary.write_utf(command_block, "c")
	command_block.put_32(complete_body.size())
	command_block.put_data(complete_body)
	var frame_stream: StreamPeerBuffer = RwBinary.writer()
	frame_stream.put_32(15)
	frame_stream.put_32(1)
	frame_stream.put_data(command_block.data_array)
	var parsed: Dictionary = RwBattleCommandReader.read_frame_packet(frame_stream.data_array)
	assert(str(parsed.get("error", "")).is_empty(), str(parsed.get("error", "")))
	var commands: Array[Dictionary] = parsed["commands"]
	var command: Dictionary = commands[0]
	assert(command["team"] == 1 and command["order_type"] == "move")
	assert(command["source_team"] == 1)
	assert(command["unit_ids"] == [42,])
	assert(command["target"] == Vector2(120.0, 80.0))
	assert(command["is_high_priority"])
	var metadata: Dictionary = command["command_targets"][42]
	assert(metadata["start_position"] == Vector2(20.0, 30.0))
	assert(metadata["target_position"] == Vector2(120.0, 80.0))
	assert(metadata["created_tick"] == 24)
	var path: Array[Vector2i] = metadata["path"]
	assert(path == [Vector2i(2, 3), Vector2i(3, 3), Vector2i(4, 3),])
	var action_frame: StreamPeerBuffer = RwBinary.writer()
	action_frame.put_32(30)
	action_frame.put_32(1)
	action_frame.put_data(RwBattleCommandWriter.write_action(1, [42,], "u_builder"))
	var action_result: Dictionary = RwBattleCommandReader.read_frame_packet(action_frame.data_array)
	assert(str(action_result.get("error", "")).is_empty())
	assert((action_result["commands"] as Array)[0]["action_id"] == "u_builder")
	var build_frame: StreamPeerBuffer = RwBinary.writer()
	build_frame.put_32(40)
	build_frame.put_32(1)
	build_frame.put_data(RwBattleCommandWriter.write_build(1, [42,], 0, Vector2(120.0, 80.0), false))
	var build_result: Dictionary = RwBattleCommandReader.read_frame_packet(build_frame.data_array)
	assert(str(build_result.get("error", "")).is_empty())
	var build_command: Dictionary = (build_result["commands"] as Array)[0]
	assert(build_command["order_type"] == "build" and build_command["source_team"] == 1)
	assert(build_command["build_unit_index"] == -2 and build_command["custom_build_unit_name"] == "extractorT1")
	assert(build_command["unit_ids"] == [42,])
	assert(RwVanillaBuildings.name_for_network_type(-2, str(build_command["custom_build_unit_name"])) == "extractor")
	assert(RwVanillaBuildings.name_for_network_type(-2, "unknown_mod_unit").is_empty())
	var factory_frame: StreamPeerBuffer = RwBinary.writer()
	factory_frame.put_32(41)
	factory_frame.put_32(1)
	factory_frame.put_data(RwBattleCommandWriter.write_build(1, [42,], 1, Vector2(140.0, 80.0), false))
	var factory_result: Dictionary = RwBattleCommandReader.read_frame_packet(factory_frame.data_array)
	assert(str(factory_result.get("error", "")).is_empty())
	assert((factory_result["commands"] as Array)[0]["build_unit_index"] == 1)
	var timeline: RwBattleTimeline = RwBattleTimeline.new()
	timeline.commands_reached.connect(_record_commands)
	timeline.reset()
	assert(timeline.receive_sync_packet(frame_stream.data_array).is_empty())
	assert(timeline.receive_sync_packet(action_frame.data_array).is_empty())
	timeline.advance(1.0 / 60.0)
	assert(_command_frames == [0,])
	for index: int in 14:
		timeline.advance(1.0 / 60.0)
	assert(timeline.current_frame == 15)
	timeline.advance(1.0 / 60.0)
	assert(_command_frames == [0, 15,])
	timeline.set_step_rate(2.0)
	var previous_frame: int = timeline.current_frame
	timeline.advance(1.0 / 60.0)
	assert(timeline.current_frame == previous_frame)
	timeline.advance(1.0 / 60.0)
	assert(timeline.current_frame == previous_frame + 1)
	print("COMMAND_READER_CHECK_OK")
	quit()


func _record_commands(frame: int, _commands: Array[Dictionary]) -> void:
	_command_frames.append(frame)
