extends RefCounted
class_name RwBuiltinActionSpecs
## 保存 RWX 内置单位的生产来源、建造动作及形态切换动作

# Generated by tools/generate_rw_builtin_action_specs.py
const SPECS: Dictionary = {
	"aaBeamGunship": {
		"built_from": [
			{
				"producer": "airFactory",
				"tech": 1,
				"position": 6.0,
				"force_nano": false,
			},
		],
		"conversions": [
			{
				"action_id": "afterburn",
				"network_id": "aaBeamGunship_afterburn_0",
				"target": "aaBeamGunship_afterburn",
				"cost": 0.0,
				"rate": 1000.0,
				"visible": true,
				"text": "i:units.aaBeamGunship.afterBurn.name",
			},
		],
	},
	"aaBeamGunship_afterburn": {
		"conversions": [
			{
				"action_id": "afterburn",
				"network_id": "aaBeamGunship_afterburn_0",
				"target": "aaBeamGunship_afterburn",
				"cost": 0.0,
				"rate": 1000.0,
				"visible": true,
				"text": "i:units.aaBeamGunship.afterBurn.name",
			},
			{
				"action_id": "cancelburn",
				"network_id": "aaBeamGunship_1",
				"target": "aaBeamGunship",
				"cost": 0.0,
				"rate": 1000.0,
				"visible": true,
				"text": "Cancel",
			},
		],
	},
	"antiNukeLauncherC": {
		"resource_actions": [
			{
				"action_id": "buildantinuke",
				"network_id": "_0",
				"resource": "ammo",
				"amount": 1.0,
				"cost": 4000.0,
				"rate": 0.0007,
				"max_stockpile": 12,
				"text": "i:gui.actions.buildAntiNuke",
				"visible": true,
			},
		],
	},
	"bomber": {
		"built_from": [
			{
				"producer": "airFactory",
				"tech": 1,
				"position": 6.0,
				"force_nano": false,
			},
		],
	},
	"bugBee": {
		"built_from": [
			{
				"producer": "bugNest",
				"tech": 1,
				"position": 4.0,
				"force_nano": false,
			},
		],
	},
	"bugExtractor": {
		"conversions": [
			{
				"action_id": "1",
				"network_id": "bugExtractorT2_0",
				"target": "bugExtractorT2",
				"cost": 1000.0,
				"rate": 0.0009,
				"visible": true,
				"text": "i:gui.actions.upgradeT2",
			},
		],
	},
	"bugFly": {
		"built_from": [
			{
				"producer": "bugNest",
				"tech": 1,
				"position": 2.0,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "bugExtractor",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "bugNest",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "bugGenerator",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "bugTurret",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"bugGenerator": {
		"conversions": [
			{
				"action_id": "1",
				"network_id": "bugGeneratorT2_0",
				"target": "bugGeneratorT2",
				"cost": 1400.0,
				"rate": 0.0002,
				"visible": true,
				"text": "i:gui.actions.upgradeT2",
			},
		],
	},
	"bugGeneratorN": {
		"conversions": [
			{
				"action_id": "1",
				"network_id": "bugGeneratorNT2_0",
				"target": "bugGeneratorNT2",
				"cost": 16000.0,
				"rate": 0.0007,
				"visible": true,
				"text": "Generator tech 2",
			},
		],
	},
	"bugMelee": {
		"built_from": [
			{
				"producer": "bugNest",
				"tech": 1,
				"position": 2.0,
				"force_nano": false,
			},
		],
	},
	"bugNest": {
		"can_build": [
			{
				"target": "setRally",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"bugPickup": {
		"built_from": [
			{
				"producer": "bugNest",
				"tech": 1,
				"position": 3.0,
				"force_nano": false,
			},
		],
	},
	"bugRanged": {
		"built_from": [
			{
				"producer": "bugNest",
				"tech": 1,
				"position": 3.0,
				"force_nano": false,
			},
		],
	},
	"bugRangedT2": {
		"built_from": [
			{
				"producer": "bugNest",
				"tech": 1,
				"position": 6.0,
				"force_nano": false,
			},
		],
	},
	"bugSpore": {
		"built_from": [
			{
				"producer": "bugNest",
				"tech": 1,
				"position": 1.0,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "bugExtractor",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "bugNest",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "bugGenerator",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "bugTurret",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"bugWasp": {
		"built_from": [
			{
				"producer": "bugNest",
				"tech": 1,
				"position": 3.0,
				"force_nano": false,
			},
		],
	},
	"c_amphibiousJet": {
		"conversions": [
			{
				"action_id": "dive",
				"network_id": "c_amphibiousJet_underwater_0",
				"target": "c_amphibiousJet_underwater",
				"cost": 0.0,
				"rate": 0.011111111111111112,
				"visible": true,
				"text": "Dive",
			},
		],
	},
	"c_amphibiousJet_transition": {
		"conversions": [
			{
				"action_id": "dive",
				"network_id": "c_amphibiousJet_underwater_0",
				"target": "c_amphibiousJet_underwater",
				"cost": 0.0,
				"rate": 0.011111111111111112,
				"visible": true,
				"text": "Dive",
			},
		],
	},
	"c_amphibiousJet_underwater": {
		"conversions": [
			{
				"action_id": "dive",
				"network_id": "c_amphibiousJet_underwater_0",
				"target": "c_amphibiousJet_underwater",
				"cost": 0.0,
				"rate": 0.011111111111111112,
				"visible": false,
				"text": "Dive",
			},
			{
				"action_id": "fly",
				"network_id": "c_amphibiousJet_1",
				"target": "c_amphibiousJet",
				"cost": 0.0,
				"rate": 0.011111111111111112,
				"visible": true,
				"text": "Fly",
			},
		],
	},
	"c_antiAirTurret": {
		"conversions": [
			{
				"action_id": "upgradet2",
				"network_id": "c_antiAirTurretT2_0",
				"target": "c_antiAirTurretT2",
				"cost": 1200.0,
				"rate": 0.001,
				"visible": true,
				"text": "i:gui.actions.upgradeToAAT2",
			},
			{
				"action_id": "upgradeflak",
				"network_id": "antiAirTurretFlak_1",
				"target": "antiAirTurretFlak",
				"cost": 4000.0,
				"rate": 0.0005,
				"visible": true,
				"text": "i:gui.actions.upgradeToAAFlak",
			},
		],
	},
	"c_antiAirTurretT2": {
		"conversions": [
			{
				"action_id": "1",
				"network_id": "c_antiAirTurretT3_0",
				"target": "c_antiAirTurretT3",
				"cost": 11000.0,
				"rate": 0.0005,
				"visible": true,
				"text": "i:gui.actions.upgradeToAAT3",
			},
		],
	},
	"c_helicopter": {
		"built_from": [
			{
				"producer": "airFactory",
				"tech": 1,
				"position": 3.0,
				"force_nano": false,
			},
		],
	},
	"c_interceptor": {
		"built_from": [
			{
				"producer": "airFactory",
				"tech": 1,
				"position": 2.0,
				"force_nano": false,
			},
		],
	},
	"c_mammothTank": {
		"built_from": [
			{
				"producer": "landFactory",
				"tech": 1,
				"position": 8.0,
				"force_nano": false,
			},
		],
	},
	"c_turret_t1": {
		"conversions": [
			{
				"action_id": "upgrade_gun",
				"network_id": "c_turret_t2_gun_0",
				"target": "c_turret_t2_gun",
				"cost": 1000.0,
				"rate": 0.001,
				"visible": true,
				"text": "i:gui.actions.upgradeToGunT2",
			},
			{
				"action_id": "upgrade_artillery",
				"network_id": "c_turret_t1_artillery_1",
				"target": "c_turret_t1_artillery",
				"cost": 1600.0,
				"rate": 0.0004,
				"visible": true,
				"text": "i:gui.actions.upgradeToArtillery",
			},
			{
				"action_id": "upgrade_flame",
				"network_id": "c_turret_t2_flame_2",
				"target": "c_turret_t2_flame",
				"cost": 700.0,
				"rate": 0.002008032128514056,
				"visible": true,
				"text": "i:gui.actions.upgradeToFlamethrower",
			},
			{
				"action_id": "upgrade_lightning",
				"network_id": "c_turret_t1_lightning_3",
				"target": "c_turret_t1_lightning",
				"cost": 2200.0,
				"rate": 0.0005747126436781609,
				"visible": true,
				"text": "i:gui.actions.upgradeToLightning",
			},
		],
	},
	"c_turret_t1_artillery": {
		"conversions": [
			{
				"action_id": "upgrade_artilleryt2",
				"network_id": "c_turret_t2_artillery_0",
				"target": "c_turret_t2_artillery",
				"cost": 9000.0,
				"rate": 0.00029976019184652276,
				"visible": true,
				"text": "i:gui.actions.upgradeToArtilleryT2",
			},
		],
	},
	"c_turret_t1_lightning": {
		"conversions": [
			{
				"action_id": "upgrade_lightningt2",
				"network_id": "c_turret_t2_lightning_0",
				"target": "c_turret_t2_lightning",
				"cost": 8000.0,
				"rate": 0.0005555555555555556,
				"visible": true,
				"text": "i:gui.actions.upgradeToLightningT2",
			},
		],
	},
	"c_turret_t2_gun": {
		"conversions": [
			{
				"action_id": "upgrade_gunt3",
				"network_id": "c_turret_t3_gun_0",
				"target": "c_turret_t3_gun",
				"cost": 11000.0,
				"rate": 0.0003,
				"visible": true,
				"text": "i:gui.actions.upgradeToGunT3",
			},
		],
	},
	"combatEngineer": {
		"built_from": [
			{
				"producer": "landFactory",
				"tech": 1,
				"position": 6.0,
				"force_nano": false,
			},
			{
				"producer": "experimentalLandFactory",
				"tech": 1,
				"position": 0.9,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "heavyTank",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "AmphibiousJet",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "extractorT2",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "landFactory",
				"tech": 2,
				"force_nano": false,
			},
			{
				"target": "airFactory",
				"tech": 2,
				"force_nano": false,
			},
			{
				"target": "mechFactoryT2",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "seaFactory",
				"tech": 2,
				"force_nano": false,
			},
			{
				"target": "fabricator",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "repairBay",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "builder",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "turretT2",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "turret",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "c_turret_t1_lightning",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "antiAirTurret",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "laserDefence",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "outpostT1",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "experimentalLandFactory",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "antiNukeLaucher",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "nukeLaucher",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "extractor",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "reclaim",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"experiementalCarrier": {
		"built_from": [
			{
				"producer": "SeaFactory",
				"tech": 1,
				"position": 10.0,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "lightGunship",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "helicopter",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "airShip",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "dropShip",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "gunShip",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "amphibiousJet",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "bomber",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "missileAirship",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "heavyInterceptor",
				"tech": 1,
				"force_nano": false,
			},
		],
		"resource_actions": [
			{
				"action_id": "buildantinuke",
				"network_id": "_9",
				"resource": "ammo",
				"amount": 1.0,
				"cost": 6000.0,
				"rate": 1000.0,
				"max_stockpile": 12,
				"text": "i:gui.actions.buildAntiNuke",
				"visible": true,
			},
		],
	},
	"experimentalDropship": {
		"built_from": [
			{
				"producer": "experimentalLandFactory",
				"tech": 1,
				"position": 5.0,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "builder",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "scout",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "combatEngineer",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "tank",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "hoverTank",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "heavyTank",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "plasmaTank",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "mammothTank",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "missileTank",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "laserTank",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"experimentalGunship": {
		"can_build": [
			{
				"target": "builder",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "scout",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "hoverTank",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "heavyHoverTank",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "combatEngineer",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "extractor",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "landFactory",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "seaFactory",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "laserDefence",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "outpostT1",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "turret",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "turretT2",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "turret_artillery",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "antiAirTurret",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "antiAirTurretT2",
				"tech": 1,
				"force_nano": false,
			},
		],
		"conversions": [
			{
				"action_id": "1",
				"network_id": "experimentalGunshipLanded_15",
				"target": "experimentalGunshipLanded",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Deploy",
			},
		],
		"resource_actions": [
			{
				"action_id": "buildantinuke",
				"network_id": "_16",
				"resource": "ammo",
				"amount": 1.0,
				"cost": 5000.0,
				"rate": 1000.0,
				"max_stockpile": 12,
				"text": "i:gui.actions.buildAntiNuke",
				"visible": true,
			},
		],
	},
	"experimentalGunshipLanded": {
		"can_build": [
			{
				"target": "builder",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "scout",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "hoverTank",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "heavyHoverTank",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "combatEngineer",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "extractor",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "landFactory",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "seaFactory",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "laserDefence",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "outpostT1",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "turret",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "turretT2",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "turret_artillery",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "antiAirTurret",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "antiAirTurretT2",
				"tech": 1,
				"force_nano": false,
			},
		],
		"conversions": [
			{
				"action_id": "1",
				"network_id": "experimentalGunship_15",
				"target": "experimentalGunship",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Undeploy",
			},
		],
		"resource_actions": [
			{
				"action_id": "buildantinuke",
				"network_id": "_16",
				"resource": "ammo",
				"amount": 1.0,
				"cost": 5000.0,
				"rate": 1000.0,
				"max_stockpile": 12,
				"text": "i:gui.actions.buildAntiNuke",
				"visible": true,
			},
		],
	},
	"experimentalSpider": {
		"built_from": [
			{
				"producer": "experimentalLandFactory",
				"tech": 1,
				"position": 6.0,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "builder",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "combatEngineer",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "heavyTank",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "heavyHoverTank",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "artillery",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "scout",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "turret",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "turret_artillery",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "antiAirTurret",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "extractor",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "landFactory",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "mechFactory",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "airFactory",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "laserDefence",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "repairBay",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "bomber",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "reclaim",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"extractorT1": {
		"conversions": [
			{
				"action_id": "upgradet2",
				"network_id": "extractorT2_0",
				"target": "extractorT2",
				"cost": 1400.0,
				"rate": 0.0006,
				"visible": true,
				"text": "i:gui.actions.upgradeT2",
			},
		],
	},
	"extractorT2": {
		"conversions": [
			{
				"action_id": "upgradet3",
				"network_id": "extractorT3_0",
				"target": "extractorT3",
				"cost": 4000.0,
				"rate": 0.0003,
				"visible": true,
				"text": "i:gui.actions.upgradeT3",
			},
		],
	},
	"extractorT3": {
		"conversions": [
			{
				"action_id": "overclock",
				"network_id": "extractorT3_overclocked_0",
				"target": "extractorT3_overclocked",
				"cost": 8000.0,
				"rate": 0.0002,
				"visible": true,
				"text": "i:units.extractor.upgrade_overclock.text",
			},
			{
				"action_id": "reinforce",
				"network_id": "extractorT3_reinforced_1",
				"target": "extractorT3_reinforced",
				"cost": 3000.0,
				"rate": 0.0007,
				"visible": true,
				"text": "i:units.extractor.upgrade_reinforce.text",
			},
		],
	},
	"extractorT3_overclocked": {
		"conversions": [
			{
				"action_id": "refund",
				"network_id": "extractorT3_1",
				"target": "extractorT3",
				"cost": 0.0,
				"rate": 0.0003333333333333333,
				"visible": true,
				"text": "i:units.extractor.downgrade_overclock.text",
			},
		],
	},
	"extractorT3_reinforced": {
		"conversions": [
			{
				"action_id": "refund",
				"network_id": "extractorT3_1",
				"target": "extractorT3",
				"cost": 0.0,
				"rate": 0.003,
				"visible": true,
				"text": "i:units.extractor.downgrade_reinforce.text",
			},
		],
	},
	"fabricatorT1": {
		"conversions": [
			{
				"action_id": "upgradet2",
				"network_id": "fabricatorT2_0",
				"target": "fabricatorT2",
				"cost": 4400.0,
				"rate": 0.00025406504065040653,
				"visible": true,
				"text": "i:gui.actions.upgradeT2",
			},
		],
	},
	"fabricatorT2": {
		"conversions": [
			{
				"action_id": "upgradet3",
				"network_id": "fabricatorT3_1",
				"target": "fabricatorT3",
				"cost": 7500.0,
				"rate": 0.0001786352268667381,
				"visible": true,
				"text": "i:gui.actions.upgradeT3",
			},
		],
	},
	"fireBee": {
		"built_from": [
			{
				"producer": "experimentalLandFactory",
				"tech": 1,
				"position": 1.0,
				"force_nano": false,
			},
		],
	},
	"heavyAAShip": {
		"built_from": [
			{
				"producer": "seaFactory",
				"tech": 1,
				"position": 5.0,
				"force_nano": false,
			},
		],
	},
	"heavyArtillery": {
		"built_from": [
			{
				"producer": "landFactory",
				"tech": 1,
				"position": 6.0,
				"force_nano": false,
			},
		],
	},
	"heavyBattleship": {
		"built_from": [
			{
				"producer": "seaFactory",
				"tech": 1,
				"position": 5.0,
				"force_nano": false,
			},
		],
	},
	"heavyInterceptor": {
		"built_from": [
			{
				"producer": "airFactory",
				"tech": 1,
				"position": 4.0,
				"force_nano": false,
			},
		],
	},
	"heavyMissileShip": {
		"built_from": [
			{
				"producer": "seaFactory",
				"tech": 1,
				"position": 6.0,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "lightSub",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"heavySub": {
		"built_from": [
			{
				"producer": "seaFactory",
				"tech": 1,
				"position": 6.0,
				"force_nano": false,
			},
		],
	},
	"lightGunship": {
		"built_from": [
			{
				"producer": "airFactory",
				"tech": 1,
				"position": 1.0,
				"force_nano": false,
			},
		],
	},
	"lightSub": {
		"built_from": [
			{
				"producer": "seaFactory",
				"tech": 1,
				"position": 2.0,
				"force_nano": false,
			},
		],
	},
	"mechArtillery": {
		"built_from": [
			{
				"producer": "mechFactory",
				"tech": 1,
				"position": 7.0,
				"force_nano": false,
			},
			{
				"producer": "mechFactoryT2",
				"tech": 1,
				"position": 7.0,
				"force_nano": false,
			},
		],
	},
	"mechBunker": {
		"built_from": [
			{
				"producer": "mechFactory",
				"tech": 1,
				"position": 7.0,
				"force_nano": false,
			},
			{
				"producer": "mechFactoryT2",
				"tech": 1,
				"position": 7.0,
				"force_nano": false,
			},
		],
		"conversions": [
			{
				"action_id": "deploy",
				"network_id": "mechBunkerDeployed_0",
				"target": "mechBunkerDeployed",
				"cost": 0.0,
				"rate": 0.006,
				"visible": true,
				"text": "Deploy",
			},
		],
	},
	"mechBunkerDeployed": {
		"conversions": [
			{
				"action_id": "deploy",
				"network_id": "mechBunkerDeployed_0",
				"target": "mechBunkerDeployed",
				"cost": 0.0,
				"rate": 0.006,
				"visible": false,
				"text": "Deploy",
			},
			{
				"action_id": "undeploy",
				"network_id": "mechBunker_1",
				"target": "mechBunker",
				"cost": 0.0,
				"rate": 0.01,
				"visible": true,
				"text": "Undeploy",
			},
		],
	},
	"mechEngineer": {
		"built_from": [
			{
				"producer": "mechFactoryT2",
				"tech": 1,
				"position": 6.0,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "reclaim",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "mechGun",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "mechMissile",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "mechBunkerDeployed",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "builderShip",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "mechFactory",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "mechFactoryT2",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "airFactory",
				"tech": 2,
				"force_nano": false,
			},
			{
				"target": "seaFactory",
				"tech": 2,
				"force_nano": false,
			},
			{
				"target": "repairBay",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "turret",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "antiAirTurret",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "laserDefence",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "outpostT1",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "extractor",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "fabricator",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "extractorT2",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "experimentalLandFactory",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "antiNukeLaucher",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "nukeLaucher",
				"tech": 1,
				"force_nano": true,
			},
		],
	},
	"mechFactory": {
		"built_from": [
			{
				"producer": "builder",
				"tech": 1,
				"position": 6.5,
				"force_nano": false,
			},
			{
				"producer": "experimentalSpider",
				"tech": 1,
				"position": 0.5,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "setRally",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "builder",
				"tech": 1,
				"force_nano": false,
			},
		],
		"conversions": [
			{
				"action_id": "upgrade",
				"network_id": "mechFactoryT2_2",
				"target": "mechFactoryT2",
				"cost": 4000.0,
				"rate": 0.0004,
				"visible": true,
				"text": "i:gui.actions.upgradeT2",
			},
		],
	},
	"mechFactoryT2": {
		"built_from": [
			{
				"producer": "experimentalSpider",
				"tech": 1,
				"position": 0.5,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "setRally",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "builder",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"mechFlame": {
		"built_from": [
			{
				"producer": "mechFactoryT2",
				"tech": 1,
				"position": 9.0,
				"force_nano": false,
			},
		],
	},
	"mechFlyingLanded": {
		"conversions": [
			{
				"action_id": "1",
				"network_id": "mechFlyingTakeoff_0",
				"target": "mechFlyingTakeoff",
				"cost": 0.0,
				"rate": 0.009,
				"visible": true,
				"text": "Fly",
			},
		],
	},
	"mechFlyingTakeoff": {
		"conversions": [
			{
				"action_id": "1",
				"network_id": "mechFlyingLanded_0",
				"target": "mechFlyingLanded",
				"cost": 0.0,
				"rate": 0.009,
				"visible": true,
				"text": "Land",
			},
		],
	},
	"mechGun": {
		"built_from": [
			{
				"producer": "mechFactory",
				"tech": 1,
				"position": 1.5,
				"force_nano": false,
			},
			{
				"producer": "mechFactoryT2",
				"tech": 1,
				"position": 1.5,
				"force_nano": false,
			},
		],
	},
	"mechHeavyMissile": {
		"built_from": [
			{
				"producer": "mechFactoryT2",
				"tech": 1,
				"position": 8.2,
				"force_nano": false,
			},
		],
	},
	"mechLaser": {
		"built_from": [
			{
				"producer": "mechFactoryT2",
				"tech": 1,
				"position": 8.1,
				"force_nano": false,
			},
		],
	},
	"mechLightning": {
		"built_from": [
			{
				"producer": "mechFactoryT2",
				"tech": 1,
				"position": 8.1,
				"force_nano": false,
			},
		],
	},
	"mechMinigun": {
		"built_from": [
			{
				"producer": "mechFactoryT2",
				"tech": 1,
				"position": 8.0,
				"force_nano": false,
			},
		],
	},
	"mechMissile": {
		"built_from": [
			{
				"producer": "mechFactory",
				"tech": 1,
				"position": 1.5,
				"force_nano": false,
			},
			{
				"producer": "mechFactoryT2",
				"tech": 1,
				"position": 1.5,
				"force_nano": false,
			},
		],
	},
	"missileAirship": {
		"built_from": [
			{
				"producer": "AirFactory",
				"tech": 1,
				"position": 6.0,
				"force_nano": false,
			},
		],
	},
	"missileTank": {
		"built_from": [
			{
				"producer": "landFactory",
				"tech": 1,
				"position": 5.0,
				"force_nano": false,
			},
		],
	},
	"modularSpider": {
		"can_build": [
			{
				"target": "builder",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "builderShip",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "combatEngineer",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "heavyTank",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "hovercraft",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "heavyHoverTank",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "artillery",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "scout",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "turret",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "turret_artillery",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "antiAirTurret",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "extractor",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "fabricatorT1",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "landFactory",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "mechFactory",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "airFactory",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "seaFactory",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "laserDefence",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "repairBay",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "bomber",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "reclaim",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"modularSpider_antiair": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
			{
				"action_id": "upgradet2",
				"network_id": "modularSpider_antiairT2_2",
				"target": "modularSpider_antiairT2",
				"cost": 16000.0,
				"rate": 0.0010416666666666667,
				"visible": true,
				"text": "Upgrade",
			},
			{
				"action_id": "upgradeflak",
				"network_id": "modularSpider_antiairFlak_3",
				"target": "modularSpider_antiairFlak",
				"cost": 10000.0,
				"rate": 0.0010416666666666667,
				"visible": true,
				"text": "Upgrade",
			},
		],
	},
	"modularSpider_antiairFlak": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"modularSpider_antiairT2": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"modularSpider_antinuke": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
		"resource_actions": [
			{
				"action_id": "buildantinuke",
				"network_id": "_2",
				"resource": "ammo",
				"amount": 1.0,
				"cost": 3000.0,
				"rate": 0.0007,
				"max_stockpile": 12,
				"text": "i:gui.actions.buildAntiNuke",
				"visible": true,
			},
		],
	},
	"modularSpider_artillery": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"modularSpider_blink": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"modularSpider_emptySlot": {
		"conversions": [
			{
				"action_id": "buildsmalllaser",
				"network_id": "modularSpider_smallgunturret_0",
				"target": "modularSpider_smallgunturret",
				"cost": 700.0,
				"rate": 1000.0,
				"visible": true,
				"text": "",
			},
			{
				"action_id": "buildgun",
				"network_id": "modularSpider_gunturret_1",
				"target": "modularSpider_gunturret",
				"cost": 2000.0,
				"rate": 1000.0,
				"visible": true,
				"text": "",
			},
			{
				"action_id": "buildlightning",
				"network_id": "modularSpider_lightning_2",
				"target": "modularSpider_lightning",
				"cost": 6000.0,
				"rate": 1000.0,
				"visible": true,
				"text": "",
			},
			{
				"action_id": "buildartillery",
				"network_id": "modularSpider_artillery_3",
				"target": "modularSpider_artillery",
				"cost": 5000.0,
				"rate": 1000.0,
				"visible": true,
				"text": "",
			},
			{
				"action_id": "buildantiair",
				"network_id": "modularSpider_antiair_4",
				"target": "modularSpider_antiair",
				"cost": 2000.0,
				"rate": 1000.0,
				"visible": true,
				"text": "",
			},
			{
				"action_id": "buildfabricator",
				"network_id": "modularSpider_fabricator_5",
				"target": "modularSpider_fabricator",
				"cost": 3000.0,
				"rate": 1000.0,
				"visible": true,
				"text": "",
			},
			{
				"action_id": "buildlaserdefense",
				"network_id": "modularSpider_laserdefense_6",
				"target": "modularSpider_laserdefense",
				"cost": 3000.0,
				"rate": 1000.0,
				"visible": true,
				"text": "",
			},
			{
				"action_id": "buildshieldgen",
				"network_id": "modularSpider_shieldGen_7",
				"target": "modularSpider_shieldGen",
				"cost": 6000.0,
				"rate": 1000.0,
				"visible": true,
				"text": "",
			},
			{
				"action_id": "buildspeed",
				"network_id": "modularSpider_speedIncomplete_8",
				"target": "modularSpider_speedIncomplete",
				"cost": 6000.0,
				"rate": 1000.0,
				"visible": true,
				"text": "",
			},
			{
				"action_id": "buildantinuke",
				"network_id": "modularSpider_antinuke_9",
				"target": "modularSpider_antinuke",
				"cost": 7000.0,
				"rate": 1000.0,
				"visible": true,
				"text": "",
			},
			{
				"action_id": "buildblink",
				"network_id": "modularSpider_blink_10",
				"target": "modularSpider_blink",
				"cost": 15000.0,
				"rate": 1000.0,
				"visible": true,
				"text": "",
			},
		],
	},
	"modularSpider_fabricator": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
			{
				"action_id": "upgradet2",
				"network_id": "modularSpider_fabricatorT2_2",
				"target": "modularSpider_fabricatorT2",
				"cost": 5000.0,
				"rate": 0.0020833333333333333,
				"visible": true,
				"text": "Upgrade",
			},
		],
	},
	"modularSpider_fabricatorT2": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"modularSpider_gunturret": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
			{
				"action_id": "upgradet2",
				"network_id": "modularSpider_gunturretT2_2",
				"target": "modularSpider_gunturretT2",
				"cost": 16000.0,
				"rate": 0.0010416666666666667,
				"visible": true,
				"text": "Upgrade",
			},
		],
	},
	"modularSpider_gunturretT2": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"modularSpider_laserdefense": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"modularSpider_lightning": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"modularSpider_nonEmpty": {
		"can_build": [
			{
				"target": "builder",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "builderShip",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "combatEngineer",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "heavyTank",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "hovercraft",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "heavyHoverTank",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "artillery",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "scout",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "turret",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "turret_artillery",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "antiAirTurret",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "extractor",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "fabricatorT1",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "landFactory",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "mechFactory",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "airFactory",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "seaFactory",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "laserDefence",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "repairBay",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "bomber",
				"tech": 1,
				"force_nano": true,
			},
			{
				"target": "reclaim",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"modularSpider_shieldGen": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"modularSpider_smallgunturret": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
			{
				"action_id": "upgradet2",
				"network_id": "modularSpider_smallgunturretT2_2",
				"target": "modularSpider_smallgunturretT2",
				"cost": 3000.0,
				"rate": 0.0010416666666666667,
				"visible": true,
				"text": "Upgrade",
			},
		],
	},
	"modularSpider_smallgunturretT2": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"modularSpider_speed": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"modularSpider_speedIncomplete": {
		"conversions": [
			{
				"action_id": "reclaim",
				"network_id": "modularSpider_emptySlot_0",
				"target": "modularSpider_emptySlot",
				"cost": 0.0,
				"rate": 0.005555555555555556,
				"visible": true,
				"text": "Reclaim Slot",
			},
		],
	},
	"nautilusSubmarine": {
		"built_from": [
			{
				"producer": "seaFactory",
				"tech": 1,
				"position": 6.0,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "lightSub",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "gunBoat",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "missileShip",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "builderShip",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "hoverTank",
				"tech": 1,
				"force_nano": false,
			},
		],
		"conversions": [
			{
				"action_id": "surface",
				"network_id": "nautilusSubmarineSurface_5",
				"target": "nautilusSubmarineSurface",
				"cost": 0.0,
				"rate": 1.0,
				"visible": true,
				"text": "Surface",
			},
			{
				"action_id": "dive",
				"network_id": "nautilusSubmarine_6",
				"target": "nautilusSubmarine",
				"cost": 0.0,
				"rate": 0.003703703703703704,
				"visible": false,
				"text": "Dive",
			},
		],
		"resource_actions": [
			{
				"action_id": "buildantinuke",
				"network_id": "cbuildAntiNuke",
				"resource": "ammo",
				"amount": 1.0,
				"cost": 6000.0,
				"rate": 1000.0,
				"max_stockpile": 4,
				"text": "i:gui.actions.buildAntiNuke",
				"visible": true,
			},
		],
	},
	"nautilusSubmarineLand": {
		"built_from": [
			{
				"producer": "experimentalLandFactory",
				"tech": 1,
				"position": 2.0,
				"force_nano": false,
			},
		],
		"can_build": [
			{
				"target": "lightSub",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "gunBoat",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "missileShip",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "builderShip",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "hoverTank",
				"tech": 1,
				"force_nano": false,
			},
		],
		"conversions": [
			{
				"action_id": "surface",
				"network_id": "nautilusSubmarineSurface_5",
				"target": "nautilusSubmarineSurface",
				"cost": 0.0,
				"rate": 1.0,
				"visible": false,
				"text": "Surface",
			},
			{
				"action_id": "dive",
				"network_id": "nautilusSubmarine_6",
				"target": "nautilusSubmarine",
				"cost": 0.0,
				"rate": 0.003703703703703704,
				"visible": false,
				"text": "Dive",
			},
			{
				"action_id": "trigger_onwater",
				"network_id": "nautilusSubmarineSurface_12",
				"target": "nautilusSubmarineSurface",
				"cost": 0.0,
				"rate": 1000.0,
				"visible": false,
				"text": "TRIGGER",
			},
		],
		"resource_actions": [
			{
				"action_id": "buildantinuke",
				"network_id": "cbuildAntiNuke",
				"resource": "ammo",
				"amount": 1.0,
				"cost": 6000.0,
				"rate": 1000.0,
				"max_stockpile": 4,
				"text": "i:gui.actions.buildAntiNuke",
				"visible": true,
			},
		],
	},
	"nautilusSubmarineSurface": {
		"can_build": [
			{
				"target": "lightSub",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "gunBoat",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "missileShip",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "builderShip",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "hoverTank",
				"tech": 1,
				"force_nano": false,
			},
		],
		"conversions": [
			{
				"action_id": "surface",
				"network_id": "nautilusSubmarineSurface_5",
				"target": "nautilusSubmarineSurface",
				"cost": 0.0,
				"rate": 1.0,
				"visible": false,
				"text": "Surface",
			},
			{
				"action_id": "dive",
				"network_id": "nautilusSubmarine_6",
				"target": "nautilusSubmarine",
				"cost": 0.0,
				"rate": 0.003703703703703704,
				"visible": true,
				"text": "Dive",
			},
		],
		"resource_actions": [
			{
				"action_id": "buildantinuke",
				"network_id": "cbuildAntiNuke",
				"resource": "ammo",
				"amount": 1.0,
				"cost": 6000.0,
				"rate": 1000.0,
				"max_stockpile": 4,
				"text": "i:gui.actions.buildAntiNuke",
				"visible": true,
			},
		],
	},
	"nukeLauncherC": {
		"resource_actions": [
			{
				"action_id": "buildnuke",
				"network_id": "_0",
				"resource": "ammo",
				"amount": 1.0,
				"cost": 11000.0,
				"rate": 0.0003,
				"max_stockpile": 4,
				"text": "i:gui.actions.buildNuke",
				"visible": true,
			},
		],
	},
	"outpostT1": {
		"conversions": [
			{
				"action_id": "upgradet2",
				"network_id": "outpostT2_0",
				"target": "outpostT2",
				"cost": 2000.0,
				"rate": 0.0004166666666666667,
				"visible": true,
				"text": "i:units.outpost.upgrade.name",
			},
		],
	},
	"plasmaTank": {
		"built_from": [
			{
				"producer": "landFactory",
				"tech": 1,
				"position": 5.0,
				"force_nano": false,
			},
		],
	},
	"robotCrab": {
		"can_build": [
			{
				"target": "repair",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "reclaim",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"robotCrabWater": {
		"can_build": [
			{
				"target": "repair",
				"tech": 1,
				"force_nano": false,
			},
			{
				"target": "reclaim",
				"tech": 1,
				"force_nano": false,
			},
		],
	},
	"scout": {
		"built_from": [
			{
				"producer": "commandCenter",
				"tech": 1,
				"position": 2.0,
				"force_nano": false,
			},
			{
				"producer": "landFactory",
				"tech": 1,
				"position": 1.1,
				"force_nano": false,
			},
		],
	},
	"spyDrone": {
		"built_from": [
			{
				"producer": "airFactory",
				"tech": 1,
				"position": 3.1,
				"force_nano": false,
			},
		],
	},
}
