extends RefCounted
class_name RwVanillaUnitCatalog
## 保存 RWX 原生类型及游戏自带自定义单位的静态目录

# Generated by tools/generate_rw_vanilla_unit_catalog.py
# Source paths are RWX references, not runtime resource paths
const NATIVE_TYPES: Array[String] = [
	"extractor",
	"landFactory",
	"airFactory",
	"seaFactory",
	"commandCenter",
	"turret",
	"antiAirTurret",
	"builder",
	"tank",
	"hoverTank",
	"artillery",
	"helicopter",
	"airShip",
	"gunShip",
	"missileShip",
	"gunBoat",
	"megaTank",
	"laserTank",
	"hovercraft",
	"ladybug",
	"battleShip",
	"tankDestroyer",
	"heavyTank",
	"heavyHoverTank",
	"laserDefence",
	"dropship",
	"tree",
	"repairbay",
	"NukeLaucher",
	"AntiNukeLaucher",
	"mammothTank",
	"experimentalTank",
	"experimentalLandFactory",
	"crystalResource",
	"wall_v",
	"fabricator",
	"attackSubmarine",
	"builderShip",
	"amphibiousJet",
	"supplyDepot",
	"experimentalHoverTank",
	"turret_artillery",
	"turret_flamethrower",
	"fogRevealer",
	"spreadingFire",
	"antiAirTurretT2",
	"turretT2",
	"turretT3",
	"damagingBorder",
	"zoneMarker",
	"editorOrBuilder",
	"dummyNonUnitWithTeam",
]

const NATIVE_REPLACEMENTS: Dictionary = {
	"extractor": "extractorT1",
	"turret": "c_turret_t1",
	"antiAirTurret": "c_antiAirTurret",
	"tank": "c_tank",
	"artillery": "c_artillery",
	"helicopter": "c_helicopter",
	"airShip": "c_interceptor",
	"laserTank": "c_laserTank",
	"NukeLaucher": "nukeLauncherC",
	"AntiNukeLaucher": "antiNukeLauncherC",
	"mammothTank": "c_mammothTank",
	"experimentalTank": "c_experimentalTank",
	"fabricator": "fabricatorT1",
	"turret_artillery": "c_turret_t1_artillery",
	"turret_flamethrower": "c_turret_t2_flame",
	"antiAirTurretT2": "c_antiAirTurretT2",
	"turretT2": "c_turret_t2_gun",
	"turretT3": "c_turret_t3_gun",
}

const STOCK_NATIVE_ACTION_IDS: Dictionary = {
	"extractor": "u_extractor",
	"landFactory": "u_landFactory",
	"airFactory": "u_airFactory",
	"seaFactory": "u_seaFactory",
	"commandCenter": "u_commandCenter",
	"turret": "u_turret",
	"antiAirTurret": "u_antiAirTurret",
	"builder": "u_builder",
	"tank": "u_tank",
	"hoverTank": "u_hoverTank",
	"artillery": "u_artillery",
	"helicopter": "u_helicopter",
	"airShip": "u_airShip",
	"gunShip": "u_gunShip",
	"missileShip": "u_missileShip",
	"gunBoat": "u_gunBoat",
	"megaTank": "u_megaTank",
	"laserTank": "u_laserTank",
	"hovercraft": "u_hovercraft",
	"ladybug": "u_ladybug",
	"battleShip": "u_battleShip",
	"tankDestroyer": "u_tankDestroyer",
	"heavyTank": "u_heavyTank",
	"heavyHoverTank": "u_heavyHoverTank",
	"laserDefence": "u_laserDefence",
	"dropship": "u_dropship",
	"tree": "u_tree",
	"repairbay": "u_repairbay",
	"NukeLaucher": "u_NukeLaucher",
	"AntiNukeLaucher": "u_AntiNukeLaucher",
	"mammothTank": "u_mammothTank",
	"experimentalTank": "u_experimentalTank",
	"experimentalLandFactory": "u_experimentalLandFactory",
	"crystalResource": "u_crystalResource",
	"wall_v": "u_wall_v",
	"fabricator": "u_fabricator",
	"attackSubmarine": "u_attackSubmarine",
	"builderShip": "u_builderShip",
	"amphibiousJet": "u_amphibiousJet",
	"supplyDepot": "u_supplyDepot",
	"experimentalHoverTank": "u_experimentalHoverTank",
	"turret_artillery": "u_turret_artillery",
	"turret_flamethrower": "u_turret_flamethrower",
	"fogRevealer": "u_fogRevealer",
	"spreadingFire": "u_spreadingFire",
	"antiAirTurretT2": "u_antiAirTurretT2",
	"turretT2": "u_turretT2",
	"turretT3": "u_turretT3",
	"damagingBorder": "u_damagingBorder",
	"zoneMarker": "u_zoneMarker",
	"editorOrBuilder": "u_editorOrBuilder",
	"dummyNonUnitWithTeam": "u_dummyNonUnitWithTeam",
}

const BUILTIN_CUSTOM_UNITS: Dictionary = {
	"aaBeamGunship": {"source": "assets/units/aa_beam_gunship/aa_beam_gunship.ini", "tech_level": 2, "built_from": ["airFactory",], "converts_to": ["aaBeamGunship_afterburn",],},
	"aaBeamGunship_afterburn": {"source": "assets/units/aa_beam_gunship/aa_beam_gunship_afterburn.ini", "tech_level": 2, "converts_to": ["aaBeamGunship",], "variant_of": "aaBeamGunship",},
	"antiAirTurretFlak": {"source": "assets/units/turrets/turret_antiair_flakgun.ini", "tech_level": 1, "upgraded_from": ["c_antiAirTurret",], "variant_of": "c_antiAirTurret",},
	"antiNukeLauncherC": {"source": "assets/units/nukes/antinuke_launcher.ini", "replaces": "AntiNukeLaucher", "tech_level": 1,},
	"bomber": {"source": "assets/units/bomber/bomber.ini", "tech_level": 2, "built_from": ["airFactory",],},
	"bugBee": {"source": "assets/units/classic_bugs/bug_bee/bug_bee.ini", "tech_level": 1, "built_from": ["bugNest",],},
	"bugExtractor": {"source": "assets/units/classic_bugs/bug_extractor/bug_extractor.ini", "tech_level": 1, "converts_to": ["bugExtractorT2",],},
	"bugExtractorT2": {"source": "assets/units/classic_bugs/bug_extractor/bug_extractorT2.ini", "tech_level": 2, "upgraded_from": ["bugExtractor",], "variant_of": "bugExtractor",},
	"bugFly": {"source": "assets/units/classic_bugs/bug_fly/bug_fly.ini", "tech_level": 1, "built_from": ["bugNest",],},
	"bugGenerator": {"source": "assets/units/classic_bugs/bug_generator/bug_generator.ini", "tech_level": 1, "converts_to": ["bugGeneratorT2",],},
	"bugGeneratorN": {"source": "assets/units/bug_base/bug_generator/bug_generator.ini", "tech_level": 1, "converts_to": ["bugGeneratorNT2",],},
	"bugGeneratorNT2": {"source": "assets/units/bug_base/bug_generator/bug_generatorT2.ini", "tech_level": 2, "variant_of": "bugGeneratorN",},
	"bugGeneratorT2": {"source": "assets/units/classic_bugs/bug_generator/bug_generatorT2.ini", "tech_level": 2, "upgraded_from": ["bugGenerator",], "variant_of": "bugGenerator",},
	"bugMelee": {"source": "assets/units/classic_bugs/bug_melee/bug_melee.ini", "tech_level": 1, "built_from": ["bugNest",],},
	"bugMeleeLarge": {"source": "assets/units/classic_bugs/bug_melee/bug_melee_large.ini", "tech_level": 1,},
	"bugMeleeSmall": {"source": "assets/units/classic_bugs/bug_melee/bug_melee_small.ini", "tech_level": 1,},
	"bugMeleeT31": {"source": "assets/units/bug_melee/bug_melee_t31.ini", "tech_level": 1,},
	"bugNest": {"source": "assets/units/classic_bugs/bug_nest/bug_nest.ini", "tech_level": 1,},
	"bugPickup": {"source": "assets/units/classic_bugs/bugs/bug_pickup.ini", "tech_level": 1, "built_from": ["bugNest",],},
	"bugRanged": {"source": "assets/units/classic_bugs/bug_ranged/bug_ranged.ini", "tech_level": 1, "built_from": ["bugNest",],},
	"bugRangedT2": {"source": "assets/units/classic_bugs/bugs_t2/bug_ranged_t2.ini", "tech_level": 1, "built_from": ["bugNest",],},
	"bugSpore": {"source": "assets/units/classic_bugs/bug_spore/bug_spore.ini", "tech_level": 1, "built_from": ["bugNest",],},
	"bugTurret": {"source": "assets/units/classic_bugs/bug_turret/bug_turret.ini", "tech_level": 1,},
	"bugWasp": {"source": "assets/units/classic_bugs/bugs/bug_wasp.ini", "tech_level": 1, "built_from": ["bugNest",],},
	"c_amphibiousJet": {"source": "assets/units/amphibious_jet/amphibious_jet.ini", "tech_level": 2, "converts_to": ["c_amphibiousJet_underwater",], "temporary_forms": ["c_amphibiousJet_transition",],},
	"c_amphibiousJet_transition": {"source": "assets/units/amphibious_jet/amphibious_jet_transition.ini", "tech_level": 2, "upgraded_from": ["c_amphibiousJet",], "variant_of": "c_amphibiousJet",},
	"c_amphibiousJet_underwater": {"source": "assets/units/amphibious_jet/amphibious_jet_underwater.ini", "tech_level": 2, "converts_to": ["c_amphibiousJet",], "temporary_forms": ["c_amphibiousJet_transition",], "upgraded_from": ["c_amphibiousJet",], "variant_of": "c_amphibiousJet",},
	"c_antiAirTurret": {"source": "assets/units/turrets/turret_antiair.ini", "replaces": "antiAirTurret", "tech_level": 1, "converts_to": ["c_antiAirTurretT2", "antiAirTurretFlak",],},
	"c_antiAirTurretT2": {"source": "assets/units/turrets/turret_antiair_t2.ini", "replaces": "antiAirTurretT2", "tech_level": 1, "converts_to": ["c_antiAirTurretT3",], "upgraded_from": ["c_antiAirTurret",], "variant_of": "c_antiAirTurret",},
	"c_antiAirTurretT3": {"source": "assets/units/turrets/turret_antiair_t3.ini", "tech_level": 1, "upgraded_from": ["c_antiAirTurret",], "variant_of": "c_antiAirTurret",},
	"c_artillery": {"source": "assets/units/tanks/artillery.ini", "replaces": "artillery", "tech_level": 1,},
	"c_experimentalTank": {"source": "assets/units/experimental_tank/experimental_tank.ini", "replaces": "experimentalTank", "tech_level": 2,},
	"c_helicopter": {"source": "assets/units/helicopter/helicopter.ini", "replaces": "helicopter", "tech_level": 1, "built_from": ["airFactory",],},
	"c_interceptor": {"source": "assets/units/interceptor/interceptor.ini", "replaces": "airShip", "tech_level": 1, "built_from": ["airFactory",],},
	"c_laserTank": {"source": "assets/units/laser_tank/laser_tank.ini", "replaces": "laserTank", "tech_level": 2,},
	"c_mammothTank": {"source": "assets/units/mammoth_tank/mammoth_tank.ini", "replaces": "mammothTank", "tech_level": 2, "built_from": ["landFactory",],},
	"c_tank": {"source": "assets/units/tanks/tank.ini", "replaces": "tank", "tech_level": 1,},
	"c_turret_t1": {"source": "assets/units/turrets/turret_t1.ini", "replaces": "turret", "tech_level": 1, "converts_to": ["c_turret_t2_gun", "c_turret_t1_artillery", "c_turret_t2_flame", "c_turret_t1_lightning",],},
	"c_turret_t1_artillery": {"source": "assets/units/turrets/turret_t1_artillery.ini", "replaces": "turret_artillery", "tech_level": 2, "converts_to": ["c_turret_t2_artillery",], "variant_of": "c_turret_t1",},
	"c_turret_t1_lightning": {"source": "assets/units/turrets/turret_t1_lightning.ini", "tech_level": 2, "converts_to": ["c_turret_t2_lightning",], "variant_of": "c_turret_t1",},
	"c_turret_t2_artillery": {"source": "assets/units/turrets/turret_t2_artillery.ini", "tech_level": 2, "variant_of": "c_turret_t1",},
	"c_turret_t2_flame": {"source": "assets/units/turrets/turret_t2_flame.ini", "replaces": "turret_flamethrower", "tech_level": 2, "variant_of": "c_turret_t1",},
	"c_turret_t2_gun": {"source": "assets/units/turrets/turret_t2_gun.ini", "replaces": "turretT2", "tech_level": 2, "converts_to": ["c_turret_t3_gun",], "variant_of": "c_turret_t1",},
	"c_turret_t2_lightning": {"source": "assets/units/turrets/turret_t2_lightning.ini", "tech_level": 2, "variant_of": "c_turret_t1",},
	"c_turret_t3_gun": {"source": "assets/units/turrets/turret_t3_gun.ini", "replaces": "turretT3", "tech_level": 2, "upgraded_from": ["c_turret_t1",], "variant_of": "c_turret_t1",},
	"combatEngineer": {"source": "assets/units/combat_engineer/combat_engineer.ini", "tech_level": 2, "built_from": ["landFactory", "experimentalLandFactory",],},
	"creditsCrates": {"source": "assets/units/resource_deposits/creditsCrate.ini", "tech_level": 1,},
	"crystal_mid": {"source": "assets/units/resource_deposits/crystal_mid.ini", "tech_level": 1,},
	"experiementalCarrier": {"source": "assets/units/experimental_carrier/Experiemental_carrier.ini", "tech_level": 2, "built_from": ["seaFactory",],},
	"experimentalDropship": {"source": "assets/units/experimental_dropship/experimental_dropship.ini", "tech_level": 1, "built_from": ["experimentalLandFactory",],},
	"experimentalGunship": {"source": "assets/units/experimental_gunship/experimental_gunship.ini", "tech_level": 1, "converts_to": ["experimentalGunshipLanded",],},
	"experimentalGunshipLanded": {"source": "assets/units/experimental_gunship/experimental_gunship_landed.ini", "tech_level": 1, "converts_to": ["experimentalGunship",], "variant_of": "experimentalGunship",},
	"experimentalSpider": {"source": "assets/units/experimental_spider/experimental_spider.ini", "tech_level": 1, "built_from": ["experimentalLandFactory",],},
	"extractorT1": {"source": "assets/units/extractor/extractor.ini", "replaces": "extractor", "tech_level": 1, "converts_to": ["extractorT2",],},
	"extractorT2": {"source": "assets/units/extractor/extractorT2.ini", "tech_level": 2, "converts_to": ["extractorT3",], "variant_of": "extractorT1",},
	"extractorT3": {"source": "assets/units/extractor/extractorT3.ini", "tech_level": 3, "converts_to": ["extractorT3_overclocked", "extractorT3_reinforced",], "variant_of": "extractorT1",},
	"extractorT3_overclocked": {"source": "assets/units/extractor/extractorT3_overclocked.ini", "tech_level": 3, "converts_to": ["extractorT3",], "variant_of": "extractorT1",},
	"extractorT3_reinforced": {"source": "assets/units/extractor/extractorT3_reinforced.ini", "tech_level": 3, "converts_to": ["extractorT3",], "variant_of": "extractorT1",},
	"fabricatorT1": {"source": "assets/units/fabricator/fabricatorT1.ini", "replaces": "fabricator", "tech_level": 1, "converts_to": ["fabricatorT2",],},
	"fabricatorT2": {"source": "assets/units/fabricator/fabricatorT2.ini", "tech_level": 2, "converts_to": ["fabricatorT3",], "upgraded_from": ["fabricatorT1",], "variant_of": "fabricatorT1",},
	"fabricatorT3": {"source": "assets/units/fabricator/fabricatorT3.ini", "tech_level": 2, "upgraded_from": ["fabricatorT1",], "variant_of": "fabricatorT1",},
	"fireBee": {"source": "assets/units/fire_bee/fire_bee.ini", "tech_level": 1, "built_from": ["experimentalLandFactory",],},
	"flare_10s": {"source": "assets/units/miscellaneous/flare_10s.ini",},
	"heavyAAShip": {"source": "assets/units/heavy_aa_ship/heavy_aa_ship.ini", "tech_level": 2, "built_from": ["seaFactory",],},
	"heavyArtillery": {"source": "assets/units/tanks/heavy_artillery.ini", "tech_level": 2, "built_from": ["landFactory",],},
	"heavyBattleship": {"source": "assets/units/heavy_battleship/heavy_battleship.ini", "tech_level": 2, "built_from": ["seaFactory",],},
	"heavyInterceptor": {"source": "assets/units/heavy_interceptor/heavyInterceptor.ini", "tech_level": 2, "built_from": ["airFactory",],},
	"heavyMissileShip": {"source": "assets/units/heavy_missile_ship/heavy_missile_ship.ini", "tech_level": 2, "built_from": ["seaFactory",],},
	"heavySub": {"source": "assets/units/heavy_sub/heavy_sub.ini", "tech_level": 2, "built_from": ["seaFactory",],},
	"laboratory": {"source": "assets/units/laboratory/laboratory.ini", "tech_level": 2,},
	"lightGunship": {"source": "assets/units/light_gunship/light_gunship.ini", "tech_level": 1, "built_from": ["airFactory",],},
	"lightSub": {"source": "assets/units/light_sub/light_sub.ini", "tech_level": 1, "built_from": ["seaFactory",],},
	"mechArtillery": {"source": "assets/units/mechs_large/mech_artillery.ini", "tech_level": 1, "built_from": ["mechFactory", "mechFactoryT2",],},
	"mechBunker": {"source": "assets/units/mechs_large/mech_bunker.ini", "tech_level": 1, "built_from": ["mechFactory", "mechFactoryT2",], "converts_to": ["mechBunkerDeployed",],},
	"mechBunkerDeployed": {"source": "assets/units/mechs_large/mech_bunker_deployed.ini", "tech_level": 1, "converts_to": ["mechBunker",], "upgraded_from": ["mechBunker",], "variant_of": "mechBunker",},
	"mechEngineer": {"source": "assets/units/mech_engineer/mech_engineer.ini", "tech_level": 2, "built_from": ["mechFactoryT2",],},
	"mechFactory": {"source": "assets/units/mech_factory/mechFactory.ini", "tech_level": 1, "built_from": ["builder", "experimentalSpider",], "converts_to": ["mechFactoryT2",],},
	"mechFactoryT2": {"source": "assets/units/mech_factory/mechFactoryT2.ini", "tech_level": 2, "built_from": ["experimentalSpider",], "upgraded_from": ["mechFactory",], "variant_of": "mechFactory",},
	"mechFlame": {"source": "assets/units/mechs_large/mech_flame.ini", "tech_level": 2, "built_from": ["mechFactoryT2",],},
	"mechFlyingLanded": {"source": "assets/units/mechs_large/mech_flying_landed.ini", "tech_level": 2, "converts_to": ["mechFlyingTakeoff",],},
	"mechFlyingTakeoff": {"source": "assets/units/mechs_large/mech_flying_takeoff.ini", "tech_level": 2, "converts_to": ["mechFlyingLanded",], "variant_of": "mechFlyingLanded",},
	"mechGun": {"source": "assets/units/mechs_small/mech_gun.ini", "tech_level": 1, "built_from": ["mechFactory", "mechFactoryT2",],},
	"mechHeavyMissile": {"source": "assets/units/mechs_large/mech_heavyMissile.ini", "tech_level": 2, "built_from": ["mechFactoryT2",],},
	"mechLaser": {"source": "assets/units/mechs_large/mech_laser.ini", "tech_level": 2, "built_from": ["mechFactoryT2",],},
	"mechLightning": {"source": "assets/units/mechs_large/mech_lightning.ini", "tech_level": 2, "built_from": ["mechFactoryT2",],},
	"mechMinigun": {"source": "assets/units/mechs_large/mech_minigun.ini", "tech_level": 2, "built_from": ["mechFactoryT2",],},
	"mechMissile": {"source": "assets/units/mechs_small/mech_missile.ini", "tech_level": 1, "built_from": ["mechFactory", "mechFactoryT2",],},
	"missileAirship": {"source": "assets/units/missile_airship/missile_airship.ini", "tech_level": 2, "built_from": ["airFactory",],},
	"missileTank": {"source": "assets/units/missile_tank/missile_tank.ini", "tech_level": 2, "built_from": ["landFactory",],},
	"missing": {"source": "assets/units/missing_unit/missing.ini", "tech_level": 1,},
	"modularSpider": {"source": "assets/units/modular_spider/modular_spider.ini", "tech_level": 1,},
	"modularSpider_antiair": {"source": "assets/units/modular_spider/antiair.ini", "tech_level": 1, "converts_to": ["modularSpider_antiairT2", "modularSpider_antiairFlak",], "variant_of": "modularSpider_emptySlot",},
	"modularSpider_antiairFlak": {"source": "assets/units/modular_spider/antiairFlak.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_antiairT2": {"source": "assets/units/modular_spider/antiairT2.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_antinuke": {"source": "assets/units/modular_spider/antinuke.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_artillery": {"source": "assets/units/modular_spider/artillery.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_blink": {"source": "assets/units/modular_spider/blink.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_emptySlot": {"source": "assets/units/modular_spider/emptySlot.ini", "tech_level": 1, "converts_to": ["modularSpider_smallgunturret", "modularSpider_gunturret", "modularSpider_lightning", "modularSpider_artillery", "modularSpider_antiair", "modularSpider_fabricator", "modularSpider_laserdefense", "modularSpider_shieldGen", "modularSpider_speedIncomplete", "modularSpider_antinuke", "modularSpider_blink",],},
	"modularSpider_fabricator": {"source": "assets/units/modular_spider/fabricator.ini", "tech_level": 1, "converts_to": ["modularSpider_fabricatorT2",], "variant_of": "modularSpider_emptySlot",},
	"modularSpider_fabricatorT2": {"source": "assets/units/modular_spider/fabricatorT2.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_gunturret": {"source": "assets/units/modular_spider/gunturret.ini", "tech_level": 1, "converts_to": ["modularSpider_gunturretT2",], "variant_of": "modularSpider_emptySlot",},
	"modularSpider_gunturretT2": {"source": "assets/units/modular_spider/gunturretT2.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_laserdefense": {"source": "assets/units/modular_spider/laser_defense.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_lightning": {"source": "assets/units/modular_spider/lightning.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_nonEmpty": {"source": "assets/units/modular_spider/modular_spider_nonEmpty.ini", "tech_level": 1, "converts_to": ["modularSpider",], "variant_of": "modularSpider",},
	"modularSpider_shieldGen": {"source": "assets/units/modular_spider/shieldGen.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_smallgunturret": {"source": "assets/units/modular_spider/smallgun.ini", "tech_level": 1, "converts_to": ["modularSpider_smallgunturretT2",], "variant_of": "modularSpider_emptySlot",},
	"modularSpider_smallgunturretT2": {"source": "assets/units/modular_spider/smallgunT2.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_speed": {"source": "assets/units/modular_spider/speed.ini", "tech_level": 1, "variant_of": "modularSpider_emptySlot",},
	"modularSpider_speedIncomplete": {"source": "assets/units/modular_spider/speed_incomplete.ini", "tech_level": 1, "converts_to": ["modularSpider_speed",], "variant_of": "modularSpider_emptySlot",},
	"nautilusSubmarine": {"source": "assets/units/nautilus/nautilus.ini", "tech_level": 2, "built_from": ["seaFactory",], "converts_to": ["nautilusSubmarineLand", "nautilusSubmarineSurface", "nautilusSubmarine",],},
	"nautilusSubmarineLand": {"source": "assets/units/nautilus/nautilusLand.ini", "tech_level": 2, "built_from": ["experimentalLandFactory",], "converts_to": ["nautilusSubmarineSurface",], "variant_of": "nautilusSubmarine",},
	"nautilusSubmarineSurface": {"source": "assets/units/nautilus/nautilusSurface.ini", "tech_level": 2, "variant_of": "nautilusSubmarine",},
	"nukeLauncherC": {"source": "assets/units/nukes/nuke_launcher.ini", "replaces": "NukeLaucher", "tech_level": 1,},
	"outpostT1": {"source": "assets/units/outpost/outpost.ini", "tech_level": 1, "converts_to": ["outpostT2",],},
	"outpostT2": {"source": "assets/units/outpost/outpostT2.ini", "tech_level": 2, "upgraded_from": ["outpostT1",], "variant_of": "outpostT1",},
	"plasmaTank": {"source": "assets/units/plasma_tank/plasma_tank.ini", "tech_level": 2, "built_from": ["landFactory",],},
	"robotCrab": {"source": "assets/units/nautilus/robotCrab/robotCrab.ini", "tech_level": 1, "converts_to": ["robotCrabWater",],},
	"robotCrabWater": {"source": "assets/units/nautilus/robotCrab/robotCrabWater.ini", "tech_level": 1, "converts_to": ["robotCrab",], "variant_of": "robotCrab",},
	"scout": {"source": "assets/units/scout/scout.ini", "tech_level": 1, "built_from": ["commandCenter", "landFactory",],},
	"spyDrone": {"source": "assets/units/spy_drone/spy_drone.ini", "tech_level": 2, "built_from": ["airFactory",],},
}


## 返回原生枚举名，索引与联机协议中的原生单位编号一致
static func native_name(index: int) -> String:
	if index < 0 or index >= NATIVE_TYPES.size():
		return ""
	return NATIVE_TYPES[index]


## 返回原生枚举编号，找不到时返回 -1
static func native_index(name: String) -> int:
	return NATIVE_TYPES.find(name)


## 返回 RWX 内置配置声明的原生类型替换名称
static func native_replacement(name: String) -> String:
	return str(NATIVE_REPLACEMENTS.get(name, ""))


## 返回替换单位对应的原生类型名
static func native_name_for_replacement(name: String) -> String:
	for native_type_name: String in NATIVE_REPLACEMENTS:
		if str(NATIVE_REPLACEMENTS[native_type_name]) == name:
			return native_type_name
	return name


## 根据最终执行的单位类型生成原版生产动作标识
static func production_action_id(unit_type_name: String) -> String:
	return "u_%s" % unit_type_name


## 返回内置自定义单位的目录记录
static func builtin_info(name: String) -> Dictionary:
	var entry: Dictionary = BUILTIN_CUSTOM_UNITS.get(name, {})
	return entry.duplicate(true)


## 返回指定目录项的原生编号或内置自定义单位网络标识
static func network_identity(name: String) -> Dictionary:
	if BUILTIN_CUSTOM_UNITS.has(name):
		return {"index": -2, "custom_name": name,}
	var index: int = native_index(name)
	if index < 0:
		return {}
	return {"index": index, "custom_name": "",}


## 按 RWX 内置替换配置返回实际优先使用的网络标识
static func preferred_network_identity(native_type_name: String) -> Dictionary:
	var replacement: String = native_replacement(native_type_name)
	if not replacement.is_empty():
		return network_identity(replacement)
	return network_identity(native_type_name)
