"""Regenerate the Godot resource UID catalog after importing RWX assets."""

import json
import re
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ASSETS_ROOT = PROJECT_ROOT / "assets" / "rwx"
OUTPUT_PATH = PROJECT_ROOT / "scripts" / "utils" / "rw_map_catalog.gd"
UID_PATTERN = re.compile(r'^uid="(uid://[^"]+)"$', re.MULTILINE)


def read_uid(import_path: Path) -> str:
    match = UID_PATTERN.search(import_path.read_text(encoding="utf-8"))
    if match is None:
        raise ValueError(f"Missing resource UID: {import_path}")
    return match.group(1)


def collect_entries(directory: Path, suffix: str, relative_keys: bool) -> dict[str, str]:
    entries: dict[str, str] = {}
    for import_path in directory.rglob(f"*.{suffix}.import"):
        key = (
            import_path.relative_to(directory).as_posix()
            if relative_keys
            else import_path.name
        ).removesuffix(".import")
        if key in entries:
            raise ValueError(f"Duplicate resource key: {key}")
        entries[key] = read_uid(import_path)
    return entries


def dictionary_lines(name: str, entries: dict[str, str]) -> list[str]:
    lines = [f"const {name}: Dictionary = {{"]
    for key in sorted(entries, key=str.casefold):
        lines.append(f"\t{json.dumps(key)}: {json.dumps(entries[key])},")
    lines.extend(["}", ""])
    return lines


def main() -> None:
    maps = collect_entries(ASSETS_ROOT / "maps" / "skirmish", "tmx", False)
    tilesets = collect_entries(ASSETS_ROOT / "tilesets", "tsx", True)
    textures = collect_entries(ASSETS_ROOT / "tilesets" / "bitmaps", "png", False)
    if not maps or not tilesets or not textures:
        raise ValueError("RWX map assets must be imported before generating the catalog")

    lines = [
        "class_name RwMapCatalog",
        "extends RefCounted",
        "",
        "# Generated by tools/generate_rw_map_catalog.py",
    ]
    lines.extend(dictionary_lines("MAP_DOCUMENTS", maps))
    lines.extend(dictionary_lines("TILESET_DOCUMENTS", tilesets))
    lines.extend(dictionary_lines("TEXTURES", textures))
    lines.extend([
        "",
        "static func list_map_names() -> Array[String]:",
        "\tvar names: Array[String] = []",
        "\tfor map_name: String in MAP_DOCUMENTS:",
        "\t\tnames.append(map_name)",
        "\treturn names",
        "",
        "",
        "static func load_map(map_name: String) -> RwXmlDocument:",
        "\tvar file_name: String = map_name.replace(\"\\\\\", \"/\").get_file()",
        "\treturn _load_document(str(MAP_DOCUMENTS.get(file_name, \"\")))",
        "",
        "",
        "static func load_tileset(source_path: String) -> RwXmlDocument:",
        "\tvar normalized: String = source_path.replace(\"\\\\\", \"/\").trim_prefix(\"./\")",
        "\tvar uid: String = str(TILESET_DOCUMENTS.get(normalized, \"\"))",
        "\tif uid.is_empty():",
        "\t\tuid = str(TILESET_DOCUMENTS.get(normalized.get_file(), \"\"))",
        "\treturn _load_document(uid)",
        "",
        "",
        "static func load_texture(image_path: String) -> Texture2D:",
        "\tvar file_name: String = image_path.replace(\"\\\\\", \"/\").get_file()",
        "\tvar uid: String = str(TEXTURES.get(file_name, \"\"))",
        "\tif uid.is_empty():",
        "\t\treturn null",
        "\treturn ResourceLoader.load(uid) as Texture2D",
        "",
        "",
        "static func _load_document(uid: String) -> RwXmlDocument:",
        "\tif uid.is_empty():",
        "\t\treturn null",
        "\treturn ResourceLoader.load(uid) as RwXmlDocument",
        "",
    ])
    with OUTPUT_PATH.open("w", encoding="utf-8", newline="\n") as output:
        output.write("\n".join(lines))
    print(f"Catalog: {len(maps)} maps, {len(tilesets)} tilesets, {len(textures)} textures")


if __name__ == "__main__":
    main()
