"""Generate native production costs and rates from the installed 1.15 game jar."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
PROBE_PATH = PROJECT_ROOT / "tools/Rw115ProductionProbe.java"
OUTPUT_PATH = PROJECT_ROOT / "scripts/utils/units/rw_native_production_specs.gd"
EXPECTED_STOCK_SHA256_PREFIX = "8a550a37e2d8a543"
ENUM_RELATIVE_PATH = Path("02b-decompiled/com/corrodinggames/rts/game/units/ar.java")


def source_native_types(source_root: Path) -> list[str]:
	path = source_root / ENUM_RELATIVE_PATH
	source = path.read_text(encoding="utf-8")
	declaration = source.split("public enum ar implements as {", 1)
	if len(declaration) != 2:
		raise ValueError("Could not locate the 1.15 native unit enum")
	entries = declaration[1].split(";", 1)[0] + ";"
	matches = re.findall(r'^\s*([A-Za-z])\("([^"]+)",\s*(\d+)\)[,;]', entries, re.MULTILINE)
	if not matches:
		raise ValueError("No native unit enum entries found")
	for index, (_, name, ordinal) in enumerate(matches):
		if int(ordinal) != index:
			raise ValueError(f"Unexpected source ordinal for {name}: {ordinal} != {index}")
	return [name for _, name, _ in matches]


def binary_specs(game_jar: Path, java: str) -> dict[str, tuple[float, float, int]]:
	digest = hashlib.sha256(game_jar.read_bytes()).hexdigest()
	if not digest.startswith(EXPECTED_STOCK_SHA256_PREFIX):
		raise ValueError(f"Game jar is not the documented 1.15 stock build: {digest}")
	classpath = os.pathsep.join((str(game_jar), str(game_jar.parent / "libs" / "*")))
	completed = subprocess.run(
		[java, "--class-path", classpath, str(PROBE_PATH)],
		check=True,
		capture_output=True,
		text=True,
		encoding="utf-8",
	)
	rows = re.findall(r"^UNIT\t(\d+)\t([^\t]+)\t[^\t]+\t([^\t]+)\t([^\t]+)$", completed.stdout, re.MULTILINE)
	frame_rows = re.findall(r"^FRAMES\t([^\t]+)\t(\d+)$", completed.stdout, re.MULTILINE)
	if len(rows) != 52:
		raise ValueError(f"Expected 52 stock enum entries, received {len(rows)}")
	if len(frame_rows) != 52:
		raise ValueError(f"Expected 52 stock completion frame rows, received {len(frame_rows)}")
	completion_frames: dict[str, int] = {name: int(frames) for name, frames in frame_rows}
	result: dict[str, tuple[float, float, int]] = {}
	for expected_ordinal, (ordinal, name, cost, rate) in enumerate(rows):
		if int(ordinal) != expected_ordinal:
			raise ValueError(f"Unexpected binary ordinal for {name}: {ordinal} != {expected_ordinal}")
		result[name] = (float(cost), float(rate), completion_frames[name])
	return result


def main() -> int:
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--source-root", required=True, type=Path)
	parser.add_argument("--game-jar", required=True, type=Path)
	parser.add_argument("--java", required=True)
	args = parser.parse_args()
	try:
		names = source_native_types(args.source_root)
		specs = binary_specs(args.game_jar, args.java)
		if list(specs) != names:
			raise ValueError("Stock binary enum does not match the 1.15 source enum")
	except (OSError, ValueError, subprocess.CalledProcessError) as error:
		print(f"RW_115_PRODUCTION_GENERATION_ERROR {error}")
		return 1

	lines = [
		"extends RefCounted",
		"class_name RwNativeProductionSpecs",
		"## 保存原版 1.15 原生单位的生产资金和每帧进度",
		"",
		"# Generated by tools/generate_rw_native_production_specs.py",
		"const SPECS: Dictionary = {",
	]
	for name in names:
		cost, rate, completion_frames = specs[name]
		lines.append(f'\t"{name}": {{"cost": {cost!r}, "rate": {rate!r}, "completion_frames": {completion_frames},}},')
	lines.extend(["}", ""])
	OUTPUT_PATH.write_bytes("\n".join(lines).encode("utf-8"))
	digest = hashlib.sha256(args.game_jar.read_bytes()).hexdigest()
	print(f"RW_115_PRODUCTION_SPECS_GENERATED units={len(names)} sha256={digest}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
