"""Extract native unit prices and production rates from the OPEN-RW enum."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from generate_rw_vanilla_unit_catalog import read_native_types


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "scripts/utils/units/rw_native_production_specs.gd"


def enum_body(source: str, unit_name: str) -> str:
    match = re.search(rf'\b{re.escape(unit_name)}\("{re.escape(unit_name)}"\)\s*\{{', source)
    if match is None:
        return ""
    depth = 1
    position = match.end()
    start = position
    while depth > 0:
        if source[position] == "{":
            depth += 1
        elif source[position] == "}":
            depth -= 1
        position += 1
    return source[start : position - 1]


def method_return(body: str, signature: str) -> float:
    match = re.search(rf"public\s+(?:int|float)\s+{signature}\s*\{{\s*return\s+([\d.Ee+-]+)f?\s*;", body)
    return float(match.group(1)) if match is not None else 0.0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rwx_root", type=Path)
    parser.add_argument("open_rw_root", type=Path)
    arguments = parser.parse_args()
    source_path = arguments.open_rw_root / "src/main/java/com/corrodinggames/rts/game/units/UnitTypeEnum.java"
    source = source_path.read_text(encoding="utf-8", errors="replace")
    lines = [
        "extends RefCounted",
        "class_name RwNativeProductionSpecs",
        "## 保存 OPEN-RW 原生枚举中的生产资金和每帧生产进度",
        "",
        "# Generated by tools/generate_rw_native_production_specs.py",
        "const SPECS: Dictionary = {",
    ]
    count = 0
    for unit_name in read_native_types(arguments.rwx_root):
        body = enum_body(source, unit_name)
        cost = method_return(body, r"c\(\)")
        rate = method_return(body, r"D\(\)")
        if cost <= 0.0 or rate <= 0.0:
            continue
        lines.append(f'\t"{unit_name}": {{"cost": {cost!r}, "rate": {rate!r},}},')
        count += 1
    lines.extend(["}", ""])
    OUTPUT_PATH.write_bytes("\n".join(lines).encode("utf-8"))
    print(f"Generated {count} native production specs")


if __name__ == "__main__":
    main()
