"""Copy RWX bundled unit images and generate their Godot UID catalog."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DESTINATION_ROOT = PROJECT_ROOT / "assets/rwx/units"
CATALOG_PATH = PROJECT_ROOT / "scripts/utils/rw_builtin_unit_image_catalog.gd"
UID_PATTERN = re.compile(r'^uid="(uid://[^"]+)"$', re.MULTILINE)


def copy_images(source_root: Path) -> int:
    count = 0
    for source in sorted(source_root.rglob("*.png")):
        destination = DESTINATION_ROOT / source.relative_to(source_root)
        destination.parent.mkdir(parents=True, exist_ok=True)
        if not destination.is_file() or destination.read_bytes() != source.read_bytes():
            shutil.copyfile(source, destination)
        count += 1
    if count == 0:
        raise ValueError(f"No RWX unit images found in {source_root}")
    return count


def generate_catalog() -> int:
    entries: dict[str, str] = {}
    for image in sorted(DESTINATION_ROOT.rglob("*.png")):
        import_path = image.with_name(image.name + ".import")
        if not import_path.is_file():
            raise FileNotFoundError(f"Import this image in Godot first: {image}")
        match = UID_PATTERN.search(import_path.read_text(encoding="utf-8"))
        if match is None:
            raise ValueError(f"Imported image has no UID: {import_path}")
        entries[image.relative_to(DESTINATION_ROOT).as_posix()] = match.group(1)
    lines = [
        "extends RefCounted",
        "class_name RwBuiltinUnitImageCatalog",
        "## 按 RWX 内置单位图片的相对路径载入已导入的 Godot 纹理",
        "",
        "# Generated by tools/import_rw_unit_images.py",
        "const TEXTURES: Dictionary = {",
    ]
    lines.extend(
        f"\t{json.dumps(key)}: {json.dumps(entries[key])},"
        for key in sorted(entries, key=str.casefold)
    )
    lines.extend([
        "}",
        "",
        "",
        "## 返回指定相对路径的纹理，找不到时返回 null",
        "static func load_texture(image_key: String) -> Texture2D:",
        "\tvar uid: String = str(TEXTURES.get(image_key, \"\"))",
        "\tif uid.is_empty():",
        "\t\treturn null",
        "\treturn ResourceLoader.load(uid) as Texture2D",
        "",
    ])
    with CATALOG_PATH.open("w", encoding="utf-8", newline="\n") as output:
        output.write("\n".join(lines))
    return len(entries)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("rwx_root", type=Path, nargs="?", help="Root of the RWX checkout")
    parser.add_argument("--catalog-only", action="store_true")
    args = parser.parse_args()
    if not args.catalog_only:
        if args.rwx_root is None:
            parser.error("rwx_root is required unless --catalog-only is used")
        count = copy_images(args.rwx_root / "assets/units")
        print(f"Copied or verified {count} unit images")
    if args.catalog_only or all(
        image.with_name(image.name + ".import").is_file()
        for image in DESTINATION_ROOT.rglob("*.png")
    ):
        print(f"Cataloged {generate_catalog()} imported unit images")
    else:
        print("Open the Godot project to import images, then rerun with --catalog-only")


if __name__ == "__main__":
    main()
