#!/usr/bin/env python

# 复用已配置的 godot-cpp，严格浮点选项只应用于本扩展
env = SConscript("godot-cpp/SConstruct").Clone()
env.Append(CPPPATH=["src/"])

if env.get("is_msvc", False):
	env.AppendUnique(CCFLAGS=["/utf-8", "/fp:strict"])
	# 使用 UTF-8 编码并可单独关闭中文源文件的代码页警告
	if ARGUMENTS.get("suppress_utf8_warnings", "yes").lower() in ("yes", "true", "1"):
		env.AppendUnique(CCFLAGS=["/wd4819"])
else:
	env.AppendUnique(CCFLAGS=["-fno-fast-math", "-ffp-contract=off"])

lib_filename = "{}rw_core{}{}".format(env.subst("$SHLIBPREFIX"), env["suffix"], env.subst("$SHLIBSUFFIX"))
library = env.SharedLibrary("project/bin/{}".format(lib_filename), source=Glob("src/*.cpp"))
Default(library)
